# Generated by Django 4.2.27 on 2025-12-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchsession_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsession',
            name='trace_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
